In [1]:
import numpy as np

In [12]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [13]:
#input
x = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])

In [15]:
#output
y = np.array([[0,1,1,0]]).T
y

array([[0],
       [1],
       [1],
       [0]])

In [6]:
np.random.seed(1)

In [8]:
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

These are the weights between input and the first hidden layer

In [9]:
syn0

array([[-0.1653904 ,  0.11737966, -0.71922612, -0.60379702],
       [ 0.60148914,  0.93652315, -0.37315164,  0.38464523],
       [ 0.7527783 ,  0.78921333, -0.82991158, -0.92189043]])

These are the weights between the hidden layer and the result 

In [10]:
syn1

array([[-0.66033916],
       [ 0.75628501],
       [-0.80330633],
       [-0.15778475]])

In [17]:
for iter in range(60000):
    # Feed forward through layers 0, 1 and 2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    #how much did we miss the target value?
    l2_error = y - l2
    
    if iter%10000 == 0 :
        #Prints the mean of the errors, after getting the absolute value 
        #np.abs(-5) = |-5|
        print(f"Error: {np.mean(np.abs(l2_error))}")
    
    l2_delta = l2_error*nonlin(l2, deriv=True)
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error * nonlin(l1, deriv=True)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)


Error: 0.49814306395090086
Error: 0.010739036268806172
Error: 0.00740748848688879
Error: 0.005984226651890311
Error: 0.005149850915331478
Error: 0.004586235779047707
