In [14]:
from __future__ import print_function
import torch

In [15]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [18]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.3598, 0.5846, 0.4420],
        [0.1530, 0.6551, 0.5629],
        [0.5195, 0.5417, 0.8784],
        [0.2717, 0.6037, 0.2884],
        [0.1500, 0.8233, 0.7639]])

In [22]:
x.size()

torch.Size([5, 3])

In [28]:
y = torch.rand(5,3)
x+y

tensor([[0.4413, 1.3925, 1.3677],
        [0.2734, 0.9081, 1.2578],
        [1.1332, 1.1054, 1.3631],
        [1.0683, 1.2867, 1.1129],
        [0.5954, 1.4595, 0.9431]])

In [29]:
y.add_(x)

tensor([[0.4413, 1.3925, 1.3677],
        [0.2734, 0.9081, 1.2578],
        [1.1332, 1.1054, 1.3631],
        [1.0683, 1.2867, 1.1129],
        [0.5954, 1.4595, 0.9431]])

In [31]:
x

tensor([[0.3598, 0.5846, 0.4420],
        [0.1530, 0.6551, 0.5629],
        [0.5195, 0.5417, 0.8784],
        [0.2717, 0.6037, 0.2884],
        [0.1500, 0.8233, 0.7639]])

In [34]:
x[:,0]

tensor([0.3598, 0.1530, 0.5195, 0.2717, 0.1500])

In [35]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)

In [36]:
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [37]:
z

tensor([[-0.3547,  0.0566,  2.1131,  0.2112,  0.3405,  0.4103,  0.4068, -0.4953],
        [ 0.6380,  0.7110, -0.2589,  0.7412, -0.4375, -2.0209,  0.5924,  0.6396]])

In [40]:
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    z, z.to("cpu", torch.double)


(tensor([[ 0.6453,  1.0566,  3.1131,  1.2112],
         [ 1.3405,  1.4103,  1.4068,  0.5047],
         [ 1.6380,  1.7110,  0.7411,  1.7412],
         [ 0.5625, -1.0209,  1.5924,  1.6396]], device='cuda:0'),
 tensor([[ 0.6453,  1.0566,  3.1131,  1.2112],
         [ 1.3405,  1.4103,  1.4068,  0.5047],
         [ 1.6380,  1.7110,  0.7411,  1.7412],
         [ 0.5625, -1.0209,  1.5924,  1.6396]], dtype=torch.float64))