In [29]:
from __future__ import print_function
import torch
import torch.nn as nn
import numpy as np

In [30]:
syn0 = torch.empty(3,5, dtype=torch.float).random_(0,1)
syn1 = torch.empty(3,5, dtype=torch.float).fill_(0.1)
l1 = torch.empty(3,5, dtype=torch.float).fill_(0.1)
syn0, syn1, l1

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]]),
 tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]]))

In [31]:
def nonlin(x, deriv=False):
    if deriv == True:
        return x * (1-x)
    return 1/(1+np.exp(-x))

In [32]:
np.random.seed(1)

In [34]:
net = nn.Sequential(
    nn.Linear(3,4),
    nn.Sigmoid(),
    nn.Linear(4,1),
    nn.Sigmoid()
)

In [45]:
x = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]]).astype('float32')
x = torch.from_numpy(x)
y = np.array([[0,1,1,0]]).T.astype('float32')
y = torch.from_numpy(y)
x,y

(tensor([[0., 0., 1.],
         [0., 1., 1.],
         [1., 0., 1.],
         [1., 1., 1.]]), tensor([[0.],
         [1.],
         [1.],
         [0.]]))

In [53]:
crit = nn.MSELoss()
crit.float()


MSELoss()

In [68]:
for j in range(2400):
    net.zero_grad()
    output = net.forward(x)
    
    loss = crit(output, y)
    gradOutput = loss.backward(output)
    
    if j % 2400 == 0:
        ?gradOutput
        
    gradInput = net.backward(X, gradOutput)
    net.updateParameters(1)
    
    if j%200 == 0:
        print(f"Error: {loss}")

AttributeError: 'Sequential' object has no attribute 'backward'

Type:        NoneType
String form: None
Docstring:   <no docstring>


In [56]:
?nn.MSELoss

Init signature: nn.MSELoss(size_average=None, reduce=None, reduction='mean')
Docstring:     
Creates a criterion that measures the mean squared error (squared L2 norm) between
each element in the input :math:`x` and target :math:`y`.

The unreduced (i.e. with :attr:`reduction` set to ``'none'``) loss can be described as:

.. math::
    \ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
    l_n = \left( x_n - y_n \right)^2,

where :math:`N` is the batch size. If :attr:`reduction` is not ``'none'``
(default ``'mean'``), then:

.. math::
    \ell(x, y) =
    \begin{cases}
        \operatorname{mean}(L), &  \text{if reduction} = \text{'mean';}\\
        \operatorname{sum}(L),  &  \text{if reduction} = \text{'sum'.}
    \end{cases}

:math:`x` and :math:`y` are tensors of arbitrary shapes with a total
of :math:`n` elements each.

The sum operation still operates over all the elements, and divides by :math:`n`.

The division by :math:`n` can be avoided if one sets ``reduction = 'sum'``.

Args:
  